name: Release

on:
  release:
    types:
      - released

jobs: 
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ steps.tag.outputs.version }}
   
    - uses: papeloto/action-zip@v1
      with:
        files: bin/Debug/net46-windows/dist
        dest: release-${{ steps.tag.outputs.version }}.zip
    
    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./release-${{ steps.tag.outputs.version }}.zip
        asset_name: release-${{ steps.tag.outputs.version }}.zip
        asset_content_type: application/zip
